# App
spring.application.name=padel

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:padeldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JSON
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Server
server.port=8080